name: Merge main into develop
on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch
          git checkout origin(develop
          git merge origin/main --no-commit --no-edit --no-ff
          git push origin develop
